### ISSUE TITLE
脚本不工作

### ISSUE THREAD

**Issue by RWDai** [Dreace/BilibiliExp#1]
可能是jquery加载有问题导致的脚本不工作 
![image](https://user-images.githubusercontent.com/27391645/75125642-ffaeb180-56f0-11ea-8e06-a0d76a524254.png)
![image](https://user-images.githubusercontent.com/27391645/75125646-0d643700-56f1-11ea-985f-ede139c61708.png)
![image](https://user-images.githubusercontent.com/27391645/75125649-1c4ae980-56f1-11ea-9cde-f80096c65f99.png)

**Comment by Dreace** [comment]
应该是 Tampermonkey 兼容问题导致，正在排查问题。

**Comment by RWDai** [comment]
我测试的时候是停用其他脚本的 刚刚我启用了另一个脚本 这个脚本也就好使了 太奇怪了 可以关issue了

**Comment by Dreace** [comment]
> 我测试的时候是停用其他脚本的 刚刚我启用了另一个脚本 这个脚本也就好使了 太奇怪了 可以关issue了

在仅开启本脚本的情况下测试也为出现依赖加载失败情况。
