### ISSUE TITLE
access_key获取方式需更新

### ISSUE THREAD

**Issue by xueyeshengdan** [Dreace/BilibiliExp#3]
https://passport.bilibili.com/login/app/third?appkey=27eb53fc9058f8c3&api=https%3A%2F%2Fwww.mcbbs.net%2Ftemplate%2Fmcbbs%2Fimage%2Fspecial_photo_bg.png&sign=04224646d1fea004e79606d3b038c84a
这个是有效的，摘自油猴脚本 ‘解除B站区域限制 by ipcjs‘

**Comment by Dreace** [comment]
明天会发一个新版本
